export const FORMAS_PAGAMENTO = ['PIX', 'DINHEIRO', 'CARTAO_DEBITO', 'CARTAO_CREDITO', 'OUTRO'];

export const STATUS_DESPESA_FORM = ['PAGO', 'PENDENTE'];

export const STATUS_DESPESA_FILTER = ['PAGO', 'PENDENTE', 'ATRASADO'];